#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-strictures
Version  : 2.000005
Release  : 5
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/strictures-2.000005.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/strictures-2.000005.tar.gz
Summary  : 'turn on strict and make most warnings fatal'
Group    : Development/Tools
License  : Artistic-1.0-Perl
BuildRequires : buildreq-cpan
BuildRequires : perl(bareword::filehandles)
BuildRequires : perl(indirect)
BuildRequires : perl(multidimensional)

%description
NAME
strictures - turn on strict and make most warnings fatal
SYNOPSIS
use strictures 2;

%package dev
Summary: dev components for the perl-strictures package.
Group: Development
Provides: perl-strictures-devel = %{version}-%{release}

%description dev
dev components for the perl-strictures package.


%prep
%setup -q -n strictures-2.000005

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/strictures.pm
/usr/lib/perl5/vendor_perl/5.28.1/strictures/extra.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/strictures.3
/usr/share/man/man3/strictures::extra.3
